StonesNatureTnWeb/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace StonesNatureTnWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public DateTime DateTime { get; set; } = DateTime.Now;
    }
}

StonesNatureTnWeb/Models/ErrorViewModel.cs
namespace StonesNatureTnWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StonesNatureTnWeb/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StonesNatureTnWeb.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public int? CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        public DateTime DateTime { get; set; }

    }
}

StonesNatureTnWeb/Models/ProductDetail.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StonesNatureTnWeb.Models
{
    public class ProductDetail
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Product Product { get; set; }
        [Required]
        public string Detail { get; set; }
    }
}

StonesNatureTnWeb/Models/ProductImage.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StonesNatureTnWeb.Models
{
    public class ProductImage
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Product product { get; set; }
        [Required]
        public string ImagePath { get; set; }
    }
}

StonesNatureTnWeb/Models/ProductSize.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StonesNatureTnWeb.Models
{
    public class ProductSize
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Product Product { get; set; }
        [Required]
        public string Size { get; set; }
    }
}

StonesNatureTnWeb/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using StonesNatureTnWeb.Data;
using StonesNatureTnWeb.Models;

namespace StonesNatureTnWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int categoryId)
        {
            ViewData["Category"] = _db.Categories.Find(categoryId);
            ViewData["Products"] = _db.Products.Where(p => p.CategoryId == categoryId).ToList();
            return View();
        }
    }
}

StonesNatureTnWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StonesNatureTnWeb.Data;
using StonesNatureTnWeb.Models;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;

namespace StonesNatureTnWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            ViewData["Categories"] = _db.Categories.ToList();
            ViewData["Products"] = _db.Products.ToList();
            ViewData["CurrentRoute"] = "Home";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            ViewData["CurrentRoute"] = "Gallery";
            return View();
        }

        public IActionResult About()
        {
            ViewData["CurrentRoute"] = "About";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["CurrentRoute"] = "Contact";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //public PartialViewResult Navbar()
        //{
        //    ViewData["Categories"] = _db.Categories.ToList();
        //    ViewData["Products"] = _db.Products.ToList();
        //    return PartialView("~/Views/Shared/_NavbarPartialView.cshtml");
        //}

        public IActionResult ContactSendEmail(string name, string email, string message)
        {
            var mailMessage = new MailMessage();

            var smtpClient = new SmtpClient("mail.stonesnaturetn.com",25);

            mailMessage.From = new MailAddress("contact@stonesnaturetn.com");
            mailMessage.To.Add("info@stonesnaturetn.com");
            //mailMessage.To.Add("harmonitechnology@gmail.com");

            mailMessage.Subject = $"{name} | Mesaj ";

            mailMessage.Body = $"<h2>Email:{email}</h2><h4>Mesaj:{message}</h5>";
            mailMessage.IsBodyHtml = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Port = 587;
            smtpClient.Credentials = new NetworkCredential("contact@stonesnaturetn.com", "StonesNature089!");
            //smtpClient.UseDefaultCredentials = true;

            smtpClient.Send(mailMessage);

            return RedirectToAction("Index");
        }
    }
}

StonesNatureTnWeb/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using StonesNatureTnWeb.Data;
using StonesNatureTnWeb.Models;

namespace StonesNatureTnWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int productId)
        {
            ViewData["Product"] = _db.Products.Find(productId);
            ViewData["ProductImages"] = _db.ProductImages.Where(p => p.ProductId == productId).ToList();
            ViewData["ProductDetails"] = _db.ProductDetail.Where(p => p.ProductId == productId).ToList();
            ViewData["ProductSizes"] = _db.ProductSize.Where(p => p.ProductId == productId).ToList();
            return View();
        }
    }
}

StonesNatureTnWeb/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StonesNatureTnWeb.Data;

namespace StonesNatureTnWeb.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;
        public NavbarViewComponent(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewData["Categories"] = _db.Categories.ToList();
            ViewData["Products"] = _db.Products.ToList();
            return View("~/Views/Home/Components/Navbar/Default.cshtml");
        }
    }
}

StonesNatureTnWeb/Views/Category/Index.cshtml
@{
    Category category = ViewData["Category"] as Category;
    IEnumerable<Product> products = ViewData["Products"] as IEnumerable<Product>;
    ViewData["Title"] = category != null ? category.Name : "Stone Nature Tn";
}

@*<h1>@category.Name</h1>
@foreach(Product product in products){
    <h2>@product.Name</h2>
}*@

<section class="section-products pt-100">
    <div class="container pb-130 mt-25">
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-6">
                <div class="header">
                    <h2>@category.Name</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Single Product -->
            @foreach (Product product in products)
            {
                <div class="col-md-12 col-lg-6 col-xl-4 text-center">
                    <div id="product-1" style="background: url(@product.ImagePath) no-repeat center; background-size:cover;" class="single-product">
                        <a asp-controller="Product" asp-action="Index" asp-route-productId="@product.Id">
                            <div class="part-1">
                            </div>
                            <div class="part-2">
                                <h3 class="product-title text-center">@product.Name</h3>
                            </div>
                        </a>
                    </div>

                </div>
            }
        </div>
    </div>
</section>

StonesNatureTnWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Us";
}

<section class="section-about pt-100">
    <div class="container pb-130 mt-25">
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-6">
                <div class="header">
                    <h2>About Stone Nature</h2>
                </div>
            </div>
        </div>
        <div class="row mt-30">

            <div class="col-lg-8 col-md-12 mt-20">
                <p>It’s a family passion that founded in 1989 Denizli, Turkey by the 1 st generation of the company.</p>
                <p>In the beginning it was small factory shop that makes cut to size and installation of the marble and travertine.</p>
                <p>By the time passes in 1996 family have started to work in its first travertine quarry located in Denizli and 2001 and 2003 they opened 2 more quarries in the same region.</p>
                <p>Family has been doing their travertine, marble and onyx exporting to more than 20 countries in the world since 1996. Over twenty five years later, the company remains within family with all members playing a key role.</p>
                <p>With acknowledging of production and mining of marble and stone Company’s 2 nd generation has decided to open their first location in Atlanta, USA on September,2016.</p>
                <p>That’s how Stones Nature inspiration has born.</p>
            </div>

            <div class="col-lg-4 col-md-12 mt-20">
                <img src="/images/about/img_1.jpg" alt="About Us">
            </div>

        </div>
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-6 mt-60">
                <div class="header">
                    <h2>Our Care And Mission</h2>
                </div>
            </div>
        </div>

        <div class="row mt-30">
            <div class="col-lg-8 col-md-12 mt-20">
                <p>For over 25 years of family experience Stones Nature has taken pride in offering the finest natural stone products, sourced from locations across the globe.</p>
                <p>Stones Nature aim is to supply vast range of marble, travertine, limestone, onyx, quartz and mosaics in tile and slab to their commercial partners with the finest premium selections.</p>
                <p>Specialising in natural stone, we have developed a purpose built warehouse outlining our extensive product range.</p>
                @*<img class="mt-20" src="/images/about/img_3.jpg" alt="About Us">*@
            </div>
            <div class="col-lg-4 col-md-12 mt-20">
                <img src="/images/about/img_2.jpg" alt="About Us">
            </div>
        </div>
    </div>
</section>

StonesNatureTnWeb/Views/Home/Components/Navbar/Default.cshtml
@{

    IEnumerable<Category> categories = ViewData["Categories"] as IEnumerable<Category>;
    IEnumerable<Product> products = ViewData["Products"] as IEnumerable<Product>;
    ViewData["CurrentRoute"] = ViewData["CurrentRoute"] != null ? ViewData["CurrentRoute"] : "";
}

<header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg">
                        <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                            <img src="/images/logo.png" alt="Logo">
                        </a> <!-- Logo -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="bar-icon"></span>
                            <span class="bar-icon"></span>
                            <span class="bar-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ml-auto">
                                <li class="nav-item @(ViewData["CurrentRoute"] == "Home" ? "active" : "")">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle no-collapse" href="#" data-bs-toggle="dropdown">Products</a>
                                    <ul class="dropdown-menu">
                                    @foreach(Category category in categories){
                                        
                                            <li><a class="dropdown-item no-collapse" asp-controller="Category" asp-action="Index" asp-route-categoryId="@category.Id"> @category.Name &raquo; </a>
                                                <ul class="submenu dropdown-menu">
                                                    @foreach(Product product in products)
                                                    {
                                                        @if(@product.CategoryId == category.Id){
                                                            <li><a class="dropdown-item" asp-controller="Product" asp-action="Index" asp-route-productId="@product.Id">@product.Name.ToUpper()</a></li>
                                                        }
                                                    }
				                                </ul>
                                            </li>
                                        
                                    }
                                    </ul>
                                    
                                </li>
                                <li class="nav-item @(ViewData["CurrentRoute"] == "Gallery" ? "active" : "")">
                                    <a class="nav-link" asp-action="Gallery" asp-controller="Home">Gallery</a>
                                </li>
                                <li class="nav-item @(ViewData["CurrentRoute"] == "About" ? "active" : "")">
                                    <a class="nav-link" asp-action="About" asp-controller="Home">About Us</a>
                                </li>
                                <li class="nav-item @(ViewData["CurrentRoute"] == "Contact" ? "active" : "")">
                                    <a class="nav-link" asp-action="Contact" asp-controller="Home">Contact</a>
                                </li>
                            </ul> <!-- navbar nav -->
                        </div>
                    </nav> <!-- navbar -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </header>

StonesNatureTnWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StonesNatureTnWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StonesNatureTnWeb.styles.css" asp-append-version="true" />
    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="/assets/images/favicon.png" type="image/png">

    <!--====== Bootstrap css ======-->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <!--====== Animate css ======-->
    <link rel="stylesheet" href="/assets/css/animate.css">

    <!--====== Magnific Popup css ======-->
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">

    <!--====== Slick css ======-->
    <link rel="stylesheet" href="/assets/css/slick.css">

    <!--====== Line Icons css ======-->
    <link rel="stylesheet" href="/assets/css/LineIcons.css">

    <!--====== Default css ======-->
    <link rel="stylesheet" href="/assets/css/default.css">

    <!--====== Style css ======-->
    <link rel="stylesheet" href="/assets/css/style.css">

    <!--====== Responsive css ======-->
    <link rel="stylesheet" href="/assets/css/responsive.css">

    <script type="text/javascript">
        //	window.addEventListener("resize", function() {
        //		"use strict"; window.location.reload();
        //	});


        document.addEventListener("DOMContentLoaded", function() {

            /////// Prevent closing from click inside dropdown
            document.querySelectorAll('.dropdown-menu').forEach(function(element) {
                element.addEventListener('click', function(e) {
                    e.stopPropagation();
                });
            })



            // make it as accordion for smaller screens
            if (window.innerWidth < 992) {

                // close all inner dropdowns when parent is closed
                document.querySelectorAll('.navbar .dropdown').forEach(function(everydropdown) {
                    everydropdown.addEventListener('hidden.bs.dropdown', function() {
                        // after dropdown is hidden, then find all submenus
                        this.querySelectorAll('.submenu').forEach(function(everysubmenu) {
                            // hide every submenu as well
                            everysubmenu.style.display = 'none';
                        });
                    })
                });

                document.querySelectorAll('.dropdown-menu a').forEach(function(element) {
                    element.addEventListener('click', function(e) {

                        let nextEl = this.nextElementSibling;
                        if (nextEl && nextEl.classList.contains('submenu')) {
                            // prevent opening link if link needs to open dropdown
                            e.preventDefault();
                            console.log(nextEl);
                            if (nextEl.style.display == 'block') {
                                nextEl.style.display = 'none';
                            } else {
                                nextEl.style.display = 'block';
                            }

                        }
                    });
                })
            }
            // end if innerWidth

        });
                                    // DOMContentLoaded  end
    </script>
</head>
<body>
    <!--====== HEADER PART START ======-->
    @await Component.InvokeAsync("Navbar")
    @*<header class="header-area">
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="index.html">
    <img src="assets/images/logo.png" alt="Logo">
    </a> <!-- Logo -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="bar-icon"></span>
    <span class="bar-icon"></span>
    <span class="bar-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul id="nav" class="navbar-nav ml-auto">
    <li class="nav-item active">
    <a class="nav-link" data-scroll-nav="0" href="#home">Home</a>
    </li>
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle no-collapse" href="#" data-bs-toggle="dropdown">Products</a>
    <ul class="dropdown-menu">
    <li><a class="dropdown-item no-collapse" href="#"> Pavers &raquo; </a>
    <ul class="submenu dropdown-menu">
    <li><a class="dropdown-item" href="#">Submenu item 1</a></li>
    <li><a class="dropdown-item" href="#">Submenu item 2</a></li>
    <li><a class="dropdown-item" href="#">Submenu item 3</a></li>
    <li><a class="dropdown-item" href="#">Submenu item 4</a></li>
    </ul>
    </li>
    </ul>
    </li>
    <li class="nav-item">
    <a class="nav-link" data-scroll-nav="0" href="#service">Services</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" data-scroll-nav="0" href="#showcase">Portfolio</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" data-scroll-nav="0" href="#team">Team</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" data-scroll-nav="0" href="#blog">Blog</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" data-scroll-nav="0" href="#contact">Contact</a>
    </li>
    </ul> <!-- navbar nav -->
    </div>
    </nav> <!-- navbar -->
    </div>
    </div> <!-- row -->
    </div> <!-- container -->
    </header>*@

    <!--====== HEADER PART ENDS ======-->
    @*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StonesNatureTnWeb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>
    </header>*@
    @*<div class="container pt-150">
    <main role="main" class="pb-3">
    @RenderBody()
    </main>
    </div>*@
    @RenderBody()

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - StonesNatureTnWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <!--====== FOOTER PART START ======-->

    <footer id="footer" class="footer-area">
        <div class="container">
            <div class="footer-widget pt-10 pb-120">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-9">
                        <div class="footer-logo mt-40">
                            <a href="#">
                                <img src="/images/small-logo-footer.png" alt="Logo">
                            </a>
                            <p class="mt-10">For over 25 years of family experience Stone Nature has taken pride in offering the finest natural stone products, sourced from locations across the globe..</p>
                            <ul class="footer-social mt-25">
                                <li><a href="https://www.facebook.com/Stone-Nature-TN-LLC-104426718978062/"><i class="lni-facebook-filled"></i></a></li>
                                <li><a href="https://instagram.com/stonenaturetn?igshid=YmMyMTA2M2Y="><i class="lni-instagram"></i></a></li>
                            </ul>
                        </div> <!-- footer logo -->
                    </div>
                    @*<div class="col-lg-3 col-md-4 col-sm-5">
                    <div class="footer-link mt-50">
                    <h5 class="f-title">Services</h5>
                    <ul>
                    <li><a href="#">Architechture Design</a></li>
                    <li><a href="#">Interior Design</a></li>
                    <li><a href="#">Autocad Services</a></li>
                    <li><a href="#">Lighting Design</a></li>
                    <li><a href="#">Poster Design</a></li>
                    </ul>
                    </div> <!-- footer link -->
                    </div>*@
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="footer-link mt-50">
                            <h5 class="f-title">Quick Links</h5>
                            <ul>
                                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><a asp-controller="Home" asp-action="Gallery">Gallery</a></li>
                                <li><a asp-controller="Home" asp-action="About">About Us</a></li>
                                <li><a asp-controller="Home" asp-action="Contact">Contact Us</a></li>
                            </ul>
                        </div> <!-- footer link -->
                    </div>
                    <div class="col-lg-5 col-md-7 col-sm-9">
                        <div class="footer-info mt-50">
                            <h5 class="f-title">Contact Info</h5>
                            <ul>
                                <li>
                                    <div class="single-footer-info mt-20">
                                        <div class="info-icon">
                                            <i class="lni-phone-handset"></i>
                                        </div>
                                        <div class="footer-info-content">
                                            <p>615 664 0820</p>
                                        </div>
                                    </div> <!-- single footer info -->
                                </li>
                                <li>
                                    <div class="single-footer-info mt-20">
                                        <div class="info-icon">
                                            <i class="lni-envelope"></i>
                                        </div>
                                        <div class="footer-info-content">
                                            <p>info@stonesnaturetn.com</p>
                                            <p>support@stonesnaturetn.com</p>
                                        </div>
                                    </div> <!-- single footer info -->
                                </li>
                                <li>
                                    <div class="single-footer-info mt-20">
                                        <div class="info-icon">
                                            <i class="lni-home"></i>
                                        </div>
                                        <div class="footer-info-content">
                                            <p>1122 Foster Ave. Ste 100 Nashville, TN 37210</p>
                                        </div>
                                    </div> <!-- single footer info -->
                                </li>
                            </ul>
                        </div> <!-- footer link -->
                    </div>
                </div> <!-- row -->
            </div> <!-- footer widget -->
            <div class="footer-copyright pt-15 pb-15">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright text-center">
                            <p>&copy; <a href="https://harmonitechnology.com" rel="nofollow">Harmoni Technology 2022</a>, All Rights Reserved.</p>
                        </div> <!-- copyright -->
                    </div>
                </div> <!-- row -->
            </div> <!--  footer copyright -->
        </div> <!-- container -->
    </footer>

    <!--====== FOOTER PART ENDS ======-->
    <!--====== BACK TO TOP PART START ======-->

    <a href="#" class="back-to-top"><i class="lni-chevron-up"></i></a>

    <!--====== BACK TO TOP PART ENDS ======-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--====== jquery js ======-->
    <script src="/assets/js/vendor/modernizr-3.6.0.min.js"></script>
    <script src="/assets/js/vendor/jquery-1.12.4.min.js"></script>

    <!--====== Bootstrap js ======-->
    <script src="/assets/js/bootstrap.min.js"></script>


    <!--====== Slick js ======-->
    <script src="/assets/js/slick.min.js"></script>

    <!--====== Magnific Popup js ======-->
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>


    <!--====== nav js ======-->
    <script src="/assets/js/jquery.nav.js"></script>

    <!--====== Nice Number js ======-->
    <script src="/assets/js/jquery.nice-number.min.js"></script>

    <!--====== Main js ======-->
    <script src="/assets/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>